In [1]:
import numpy as np


In [28]:
a=np.array([1,2,3])
print(a)
print(a*2)
print(a+5)
print(a-5)

[1 2 3]
[2 4 6]
[6 7 8]
[-4 -3 -2]


In [5]:
table=np.array([[3,5,6],[8,9,3]])
print(table.ndim)
print(table.size)
print(table.shape)
print(table.dtype)

2
6
(2, 3)
int64


In [10]:
#creating the arrays quickly
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [15]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [16]:
# 1.creating an array
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a.shape)
print(a.dtype)

(10,)
int64


In [18]:
#2.creting 3x3 ones and zeros array
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
t=np.arange(1,10).reshape(3,3)
print(t)
print(t[1,2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [24]:
print(a[  : : -1])

[10  9  8  7  6  5  4  3  2  1]


In [25]:
x=np.array([3,8,1,9,4,7])
print(x[x>5])

[8 9 7]


In [27]:
x[x<4]=0
print(x) #printing the elements in the x which are lessthan 4

[0 8 0 9 4 7]
